version: '3'

services:
  api:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:api --host 0.0.0.0'
    container_name: fastapi_nota
    volumes:
      - .:/app
    restart: always
    ports:
      - 8001:8000
    depends_on:
      - db

  db:
    image: postgres:15.1
    container_name: postgres_nota
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=notaDB
    volumes:
      - postgres_nota:/var/lib/postgresql/data

volumes:
  postgres_nota:
